fix: element tab tooltip cutoff
bpmn-io/variable-outline pull request #3
Opened 2024-09-08 22:52 UTC by abdul99ahad

### Proposed Changes

 

Fixed Element tab tooltip cutting off 

### Checklist

To ensure you provided everything we need to look at your PR:

* [ ] **Brief textual description** of the changes present
* [ ] **Visual demo** attached
* [ ] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [ ] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

Related to: https://github.com/camunda/camunda-modeler/issues/4496

2024-09-09 08:58 UTC, philippfromme commented
The fix I had in mind wouldn't try to fit the tooltips inside a specific container but would put them on top of everything just like the properties panel tooltips.

![brave_ZbRMvD0ZiN](https://github.com/user-attachments/assets/d23ef09e-4ab2-4ff6-b9d6-e5219c24ff0f)

2024-09-09 09:03 UTC, philippfromme requested changes
Regardless of _how_ we fix the issue we need to make sure we fix it for _all_ tooltips.

2024-09-09 10:10 UTC, nikku commented
@abdul99ahad from my investigations the issue is a miss-use of `overflow`, cf. capture below:

![capture AyetlV_optimized](https://github.com/user-attachments/assets/123e5843-6601-44e6-bdf1-4b28a8c169e6)

2024-09-09 10:25 UTC, abdul99ahad commented
> @abdul99ahad from my investigations the issue is a miss-use of `overflow`, cf. capture below:
> 
> ![capture AyetlV_optimized](https://private-user-images.githubusercontent.com/58601/365608607-123e5843-6601-44e6-bdf1-4b28a8c169e6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4Nzc1NzIsIm5iZiI6MTcyNTg3NzI3MiwicGF0aCI6Ii81ODYwMS8zNjU2MDg2MDctMTIzZTU4NDMtNjYwMS00NGU2LWJkZjEtNGIyOGE4YzE2OWU2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDEwMjExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmMmQzOWMxMTAyNzM1NmQ5MDY0MjhiNTAxZDExZmJhY2JmMmEyMDZkZjk3ZjFkZjMzYTE3NzAyZjVlYzc3YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RHrLFB_bGNT3xtxsHuMlXPwPAP65Eh8tOQDKpZklWWg) [ ![capture AyetlV_optimized](https://private-user-images.githubusercontent.com/58601/365608607-123e5843-6601-44e6-bdf1-4b28a8c169e6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4Nzc1NzIsIm5iZiI6MTcyNTg3NzI3MiwicGF0aCI6Ii81ODYwMS8zNjU2MDg2MDctMTIzZTU4NDMtNjYwMS00NGU2LWJkZjEtNGIyOGE4YzE2OWU2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDEwMjExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmMmQzOWMxMTAyNzM1NmQ5MDY0MjhiNTAxZDExZmJhY2JmMmEyMDZkZjk3ZjFkZjMzYTE3NzAyZjVlYzc3YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RHrLFB_bGNT3xtxsHuMlXPwPAP65Eh8tOQDKpZklWWg) ](https://private-user-images.githubusercontent.com/58601/365608607-123e5843-6601-44e6-bdf1-4b28a8c169e6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4Nzc1NzIsIm5iZiI6MTcyNTg3NzI3MiwicGF0aCI6Ii81ODYwMS8zNjU2MDg2MDctMTIzZTU4NDMtNjYwMS00NGU2LWJkZjEtNGIyOGE4YzE2OWU2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDEwMjExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmMmQzOWMxMTAyNzM1NmQ5MDY0MjhiNTAxZDExZmJhY2JmMmEyMDZkZjk3ZjFkZjMzYTE3NzAyZjVlYzc3YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RHrLFB_bGNT3xtxsHuMlXPwPAP65Eh8tOQDKpZklWWg) [ ](https://private-user-images.githubusercontent.com/58601/365608607-123e5843-6601-44e6-bdf1-4b28a8c169e6.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4Nzc1NzIsIm5iZiI6MTcyNTg3NzI3MiwicGF0aCI6Ii81ODYwMS8zNjU2MDg2MDctMTIzZTU4NDMtNjYwMS00NGU2LWJkZjEtNGIyOGE4YzE2OWU2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDEwMjExMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmMmQzOWMxMTAyNzM1NmQ5MDY0MjhiNTAxZDExZmJhY2JmMmEyMDZkZjk3ZjFkZjMzYTE3NzAyZjVlYzc3YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RHrLFB_bGNT3xtxsHuMlXPwPAP65Eh8tOQDKpZklWWg)

Yes @nikku, you’re right. The overflow property is preventing the tooltip from hovering over other elements. I’ve spent a lot of time trying different solutions, but the only one that seems to work is removing the overflow property, which isn’t feasible. As a result, I had to restrict the tooltip to stay within the container.

2024-09-18 07:39 UTC, nikku commented
Did some more research and found the upstream bug report: https://github.com/carbon-design-system/carbon/issues/14677.

I propose we solve this either by implementing a proper (global, `position: fixed`) tooltip (we don't use Carbon UI for the time being) _or_ not at all. To me it does not feel right to workaround with a what looks like "local" CSS fix. 

As you proposed this PR, could you evaluate @abdul99ahad: Is this something that is robust enough, and also works for other tooltips that we may introduce, or is this just a quick workaround? If it is the later, then I'd rather not merge this (today) but consider another direction.

2024-09-18 12:39 UTC, closed without merging

2024-09-18 12:39 UTC, nikku commented
As discussed we'll close this PR in favor of a controlled update of our tooltip infrastructure, some day maybe.

If we fix the tips, we want to fix them alltogether.